"""empty message

Revision ID: 1411dc374a81
Revises: 5bbbccdb575b
Create Date: 2019-02-12 20:34:24.815000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1411dc374a81'
down_revision = '5bbbccdb575b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accidents_stat', 'acc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'accidents_stat', 'accidents', ['acc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accidents_stat', type_='foreignkey')
    op.alter_column('accidents_stat', 'acc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
