"""empty message

Revision ID: 5bbbccdb575b
Revises: 29543aa09e95
Create Date: 2019-02-12 20:24:09.804000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbbccdb575b'
down_revision = '29543aa09e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accidents_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc_id', sa.Integer(), nullable=False),
    sa.Column('acc_no_uninjured', sa.Integer(), nullable=False),
    sa.Column('acc_no_minor', sa.Integer(), nullable=False),
    sa.Column('acc_no_major', sa.Integer(), nullable=False),
    sa.Column('acc_no_dead', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc_title', sa.String(length=128), nullable=False),
    sa.Column('acc_desc', sa.Text(), nullable=False),
    sa.Column('acc_time', sa.Text(), nullable=False),
    sa.Column('acc_location', sa.String(length=250), nullable=False),
    sa.Column('acc_involved', sa.String(length=250), nullable=False),
    sa.Column('acc_is_victim', sa.Boolean(), nullable=True),
    sa.Column('acc_photo', sa.String(length=100), nullable=False),
    sa.Column('acc_created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acc_created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accidents')
    op.drop_table('accidents_stat')
    # ### end Alembic commands ###
