"""empty message

Revision ID: 6e24830faa31
Revises: b7ab66266d00
Create Date: 2019-02-20 14:19:36.863756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e24830faa31'
down_revision = 'b7ab66266d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accidents', sa.Column('acc_area_name', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accidents', 'acc_area_name')
    # ### end Alembic commands ###
