"""empty message

Revision ID: c9fb3930a46c
Revises: 1411dc374a81
Create Date: 2019-02-12 20:38:16.508000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fb3930a46c'
down_revision = '1411dc374a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accidents_stat', ['acc_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accidents_stat', type_='unique')
    # ### end Alembic commands ###
